export const CHARACTERS_2 = {
    high_spore_speaker: { name: "High Spore Speaker", role: "Cult Leader of the Toad Cult", description: "The enigmatic and charismatic leader of the Toad Cult. They claim to receive visions from 'The Ascended One' and guide their followers with prophecies of a world reclaimed by fungal growth. Their sanity is a subject of much debate." },
    lord_crimson: { name: "Lord Crimson", role: "Elder Vampire of the Onyx Hand", description: "An ancient and manipulative vampire who plays the long game of politics with centuries of experience. Lord Crimson orchestrated Archie's acquittal purely to sow chaos within the rival Mages' Guild, viewing mortals as pawns in his grand designs. He is patience and cruelty incarnate." },
    archmage_theron: { name: "Archmage Theron", role: "Conservator Leader, Mages' Guild", description: "The stern and traditionalist former leader of the Mages' Guild. Theron believes that magic is a dangerous force that must be strictly controlled and regulated. He now leads the powerful Conservator faction within the Guild's divided Conclave." },
    chief_thornpaw: { name: "Chief Thornpaw", role: "Spirit-Walker Leader of the Rakasha Clans", description: "The wise and patient shaman who leads the Rakasha Clans. He is deeply connected to the spirits of the natural world and values balance above all. He has taken Dan under his tutelage, and holds a deep secret: a past relationship with the late Princess Peach, which gives him unique insight into the kingdom's history." },
    the_jester: { name: "The Cosmic Jester", role: "Chaotic Deity of the Cosmic Jesters", description: "An unknowable, god-like entity of pure chaos and madness. The Cosmic Jester's motives are incomprehensible, and its followers believe that acts of randomness, illogic, and spectacular failure are the highest forms of prayer." },
    high_inquisitor_vale: { name: "High Inquisitor Vale", role: "Leader of the Silver Flame", description: "The zealous and unwavering leader of the Order of the Silver Flame. Vale sees the world in stark black and white, viewing all supernatural creatures, unsanctioned magic-users, and moral ambiguity as a corruption that must be purged with holy fire. His righteousness is as dangerous as it is pure." },
    judge_eternal_korven: { name: "Judge Eternal Korven", role: "Supreme Arbiter of the Oathbound", description: "The ancient and immortal leader of the Oathbound Judges. Korven is the living embodiment of cosmic law, utterly impartial and unyielding. He does not care for motive or circumstance, only for the letter of the law and the maintenance of universal order." },
    warboss_skarjaw: { name: "Warboss Skarjaw", role: "Big Boss of Da Krumperz", description: "The biggest, strongest, and most cunning Ork in a generation. Skarjaw leads his WAAAGH! with an iron fist and a love for a good fight. He respects strength above all else and is always looking for his next big scrap, viewing the world as a series of targets to be krumped." },
    clan_chief_redmane: { name: "Clan Chief Redmane", role: "Leader of the Rebel Clans' Old Guard", description: "A proud and traditionalist leader who fights to preserve the ancient ways of his people against the encroaching Regal Empire. He is deeply suspicious of outsiders, especially monarchs like Bowser, and sees their 'help' as just another form of conquest." },
    captain_syrup: { name: "Captain Syrup", role: "Fleet Captain of the Crimson Fleet", description: "The infamous and cunning pirate captain of the Crimson Fleet. After being freed by the party only to be immediately embroiled in another conflict, she holds a serious grudge. She is driven by a thirst for treasure, revenge, and the freedom of the open skies." },
    boss_knuckles: { name: "Boss Knuckles", role: "Leader of the Iron Fists", description: "The brutal and vengeful leader of the Iron Fists gang. After the party dismantled one of his most profitable smuggling operations, Knuckles has made it his personal mission to see them all dead, placing a massive bounty on their heads and dedicating his resources to their destruction." },
    alpha_bloodmaw: { name: "Alpha Bloodmaw", role: "Pack Alpha of the Moonfang Pack", description: "A ferocious and territorial werewolf chieftain. He rules a powerful Den Pack through sheer strength and dominance, and his hatred for the vampires of the Onyx Hand is legendary. He is a key subordinate to the Alpha Prime." },
    captain_toad: { name: "Captain Toad", role: "Commander of the Toadstool Guard, Mushroom Regency", description: "The brave but perpetually overwhelmed commander of the Regency's official military. He is a loyal soldier doing his best to protect his people in a time of unprecedented crisis, caught between the political maneuvering of the Regency and the fanatical zeal of the Peach Loyalists." },
    captain_toadette: { name: "Captain Toadette", role: "Leader of the Peach Loyalists", description: "A fierce and fanatical figure within the Mushroom Kingdom Civil War, her small, stout frame measuring three feet tall, a testament to her unyielding resolve. Her vibrant magenta mushroom cap, adorned with irregular white spots, sits tilted forward, framing large black eyes that blaze with an intense, almost manic determination. She wears a tattered blue vest and a crimson scarf, a vivid symbol of her defiance. Her gloved hands grip a weathered staff, a tool of both command and retribution in her relentless quest to find the 'true' heir and hold Bowser accountable for the chaos that led to the Princess's death, viewing the Regency's diplomatic approach as weakness." },
    kamek: { name: "Kamek", role: "Chief Advisor to Bowser, Leader of the Koopa Remnants", description: "The ancient and powerful Magikoopa who serves as Bowser's most trusted advisor. With Bowser allied with the party, Kamek has been left to command the scattered Koopa Troop remnants, using his cunning to keep them from being completely destroyed." },
    fawful: { name: "Fawful", role: "Master of Chortles, Lord of the Castle", description: "A cunning and erratic Beanish villain known for his maniacal laughter and green-hued schemes. He has seized Peach's Castle and transformed it into a twisted stronghold filled with his mechanical minions and an oversized vacuum device." },
    eager: { name: "Eager", role: "Swift Scout of the Liberated Toads", description: "A nimble and quick-witted toad who prefers to keep his distance, using his whip to control the battlefield and scout ahead for his slower brethren." },
    ryan: { name: "Ryan", role: "Arcane Student of the Liberated Toads", description: "A quiet, studious toad with a natural but untrained affinity for magic. He watches Dan's training with intense focus, hoping to unlock his own arcane potential." },
    roger: { name: "Roger", role: "Pragmatist Gunner of the Liberated Toads", description: "A practical and no-nonsense toad who sees the world for what it is. He found a discarded firearm during their escape and has become a surprisingly skilled marksman." },
    bones: { name: "Bones", role: "Hardened Survivor of the Liberated Toads", description: "A tough, grotesque-looking toad who has seen the worst of the world and survived. He is resilient and cynical, and is currently wrestling with the strange 'debt' he feels he owes to the Orcs who kidnapped and then spared him." },
    detective_penny: { name: "Detective Penny", role: "Lead Investigator, Diamond City Investigators", description: "A sharp-witted detective with a passion for puzzles and justice. She has made it her personal mission to dismantle Wario's criminal empire, one recovered artifact at a time." },
    master_goodstyle: { name: "Master Goodstyle", role: "Patron, The Goodstyle Artisans", description: "An ancient and revered artisan who believes that beauty is the world's most valuable currency. He despises Wario for his crude materialism and constant theft of priceless cultural treasures." },
    fangscar_the_elder: {
        name: "Fangscar the Elder",
        role: "Alpha Prime of the Moonfang Pack",
        description: "The supreme leader of the Moonfang werewolf confederation, a massive werewolf whose silver fur is crisscrossed with scars from countless challenges. He is chosen through ritual combat and leads through a combination of primal strength and battle-hardened wisdom."
    },
    archmage_veyra: {
        name: "Archmage Veyra",
        role: "Archmage Sovereign of the Mages' Guild",
        description: "The current leader of the Mages' Guild, elected by the Grand Conclave. A member of the traditionalist Conservator faction, she now struggles to mediate the escalating tensions between her own party and the radical Innovators, all while upholding the Guild's arcane laws."
    },
    'janna_brightspark': {
        name: "Janna Brightspark",
        role: "Innovator Leader, Mages' Guild",
        description: "A brilliant but reckless mage who leads the radical Innovator faction. She believes that magical progress should be pursued at any cost, viewing tradition as a cage that stifles true discovery. Her experiments often push the boundaries of what is considered safe or ethical, making her a controversial but undeniably powerful figure within the Guild's Conclave."
    }
};